### PR TITLE
Update installation.md

### PR DESCRIPTION
**Pull request by nelg**
Added arch Linux package

### CODE REVIEW

**Comment by busser** [comment]
Love this ❤️ Thanks a lot for contributing!

Is there some automation in place to update the package when we release a new version of tfautomv?

**Comment by busser** [comment]
We currently use goreleaser for release automation. Thanks to your PR, I looked into whether goreleaser supports AUR [and it does](https://goreleaser.com/customization/aur/). I've given it a try and goreleaser is able to generate AUR manifests that allow installing a pre-built binary. This differs from your package, where tfautomv is built from source.

Reading through [AUR submission guidelines](https://wiki.archlinux.org/title/AUR_submission_guidelines), is says:
> Packages that use prebuilt deliverables](https://en.wikipedia.org/wiki/Deliverable), when the sources are available, must use the `-bin` suffix.

So the package generated with goreleaser would be named `tfautomv-bin`, which does not conflict with your package named `tfautomv`.

So here is what I am going to do:
1. I approve your PR as is. Again, thank you for contributing!
2. I implement work on the `tfautomv-bin` package.
3. I update the docs to mention both `tfautomv` and `tfautomv-bin`, specifying that `tfautomv-bin` is automatically updated.
4. (Optional) Someone (maybe you!) automates updates of the `tfautomv` package, and we update the docs accordingly.

Does that seem faire to you? 🙂

**Review by busser — APPROVED** [review]

**Comment by nelg** [comment]
> Love this heart Thanks a lot for contributing!
> 
> Is there some automation in place to update the package when we release a new version of tfautomv?

No automatic updates I've made, But I don't mind if we figure out a way to do so.
Repo is: ssh://aur@aur.archlinux.org/tfautomv.git

happy to add you as a maintainer/contributor/owner   - I don't think there is anything that would stop you editing this repo if you have an aur account.

**Comment by nelg** [comment]
> We currently use goreleaser for release automation. Thanks to your PR, I looked into whether goreleaser supports AUR [and it does](https://goreleaser.com/customization/aur/). I've given it a try and goreleaser is able to generate AUR manifests that allow installing a pre-built binary. This differs from your package, where tfautomv is built from source.
> 
> Reading through [AUR submission guidelines](https://wiki.archlinux.org/title/AUR_submission_guidelines), is says:
> 
> > Packages that use prebuilt deliverables](https://en.wikipedia.org/wiki/Deliverable), when the sources are available, must use the `-bin` suffix.
> 
> So the package generated with goreleaser would be named `tfautomv-bin`, which does not conflict with your package named `tfautomv`.
> 
> So here is what I am going to do:
> 
>     1. I approve your PR as is. Again, thank you for contributing!
> 
>     2. I implement work on the `tfautomv-bin` package.
> 
>     3. I update the docs to mention both `tfautomv` and `tfautomv-bin`, specifying that `tfautomv-bin` is automatically updated.
> 
>     4. (Optional) Someone (maybe you!) automates updates of the `tfautomv` package, and we update the docs accordingly.
> 
> 
> Does that seem faire to you? slightly_smiling_face

The bin version is OK as well, so I'm happy.

**Comment by nelg** [comment]
Do you know what architectures GO will compile for?

At the moment I just have set x86_64 because that's what I have.

https://wiki.archlinux.org/title/PKGBUILD#arch

**Pull request merged**
